/**
 * WorkTrain Report Schedule Installer
 *
 * Installs a recurring job that runs `worktrain report --days 30 --out ~/.workrail/data/reports/latest.json`
 * on a daily or weekly schedule.
 *
 * Platform support:
 * - macOS (darwin): launchd plist written to ~/Library/LaunchAgents/io.workrail.report.plist
 * - Linux/other: crontab entry added via `crontab -l | { cat; echo "..."; } | crontab -`
 *
 * Design:
 * - Pure function: all I/O injected via WorktrainReportScheduleDeps
 * - Never emits JSON to stdout (schedule mode is mutually exclusive with report output)
 * - Errors are returned as Result-style values, not thrown
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ScheduleFrequency = 'daily' | 'weekly';

export interface WorktrainReportScheduleDeps {
  /** The detected platform string (process.platform). */
  readonly platform: string;
  /** Path to the worktrain binary (process.argv[1] or 'worktrain'). */
  readonly worktrainBinPath: string;
  /** Path to the node binary (process.execPath). */
  readonly nodeBinPath: string;
  /** Return the home directory. */
  readonly homedir: () => string;
  /** Join path segments. */
  readonly joinPath: (...parts: string[]) => string;
  /** Write a file at the given path (creates parent directories as needed). */
  readonly writeFile: (filePath: string, content: string) => Promise<void>;
  /** Make a directory (recursive). */
  readonly mkdir: (dirPath: string) => Promise<void>;
  /**
   * Execute a shell command. Returns stdout, stderr, and exit code.
   * Used for crontab manipulation on Linux.
   */
  readonly exec: (command: string, args: string[]) => Promise<{ stdout: string; stderr: string; exitCode: number }>;
  /** Write a line to stdout (confirmation message to the user). */
  readonly print: (line: string) => void;
  /** Write a line to stderr (warnings and errors). */
  readonly printErr: (line: string) => void;
}

/** Result of a schedule install attempt. */
export type ScheduleInstallResult =
  | { readonly kind: 'ok'; readonly detail: string }
  | { readonly kind: 'err'; readonly message: string };

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const LAUNCHD_LABEL = 'io.workrail.report';
const PLIST_FILENAME = `${LAUNCHD_LABEL}.plist`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Escape the five XML special characters. */
function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Build a launchd plist that runs `worktrain report --days 30 --out <outputPath>`
 * on the given frequency.
 *
 * Daily: StartCalendarInterval Hour=6, Minute=0 (6 AM local time)
 * Weekly: StartCalendarInterval Weekday=1, Hour=6, Minute=0 (Monday 6 AM local time)
 *
 * WHY 6 AM: generates overnight data before the work day starts without interfering
 * with active work. A reasonable default; users can edit the plist to adjust.
 */
function buildReportPlist(
  nodeBinPath: string,
  worktrainBinPath: string,
  outputPath: string,
  homeDir: string,
  frequency: ScheduleFrequency,
): string {
  const scheduleBlock =
    frequency === 'weekly'
      ? `
  <key>StartCalendarInterval</key>
  <dict>
    <key>Weekday</key><integer>1</integer>
    <key>Hour</key><integer>6</integer>
    <key>Minute</key><integer>0</integer>
  </dict>`
      : `
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>6</integer>
    <key>Minute</key><integer>0</integer>
  </dict>`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(nodeBinPath)}</string>
    <string>${escapeXml(worktrainBinPath)}</string>
    <string>report</string>
    <string>--days</string>
    <string>30</string>
    <string>--out</string>
    <string>${escapeXml(outputPath)}</string>
  </array>

  <key>WorkingDirectory</key>
  <string>${escapeXml(homeDir)}</string>
${scheduleBlock}

  <!--
    Generated by: worktrain report --schedule ${frequency}
    Output: ${outputPath}
    To remove: launchctl unload ~/Library/LaunchAgents/${PLIST_FILENAME} && rm ~/Library/LaunchAgents/${PLIST_FILENAME}
  -->
</dict>
</plist>
`;
}

/**
 * Build the cron schedule expression for the given frequency.
 * Daily: 0 6 * * *  (6:00 AM every day)
 * Weekly: 0 6 * * 1  (6:00 AM every Monday)
 */
function buildCronExpression(frequency: ScheduleFrequency): string {
  return frequency === 'weekly' ? '0 6 * * 1' : '0 6 * * *';
}

// ---------------------------------------------------------------------------
// Main installer
// ---------------------------------------------------------------------------

/**
 * Install a recurring schedule for `worktrain report`.
 *
 * On macOS: writes a launchd plist and loads it with launchctl.
 * On Linux/other: adds a crontab entry.
 *
 * Returns a ScheduleInstallResult describing the outcome.
 * Never throws -- errors are returned as { kind: 'err' }.
 */
export async function installReportSchedule(
  deps: WorktrainReportScheduleDeps,
  frequency: ScheduleFrequency,
): Promise<ScheduleInstallResult> {
  const homeDir = deps.homedir();
  const outputPath = deps.joinPath(homeDir, '.workrail', 'data', 'reports', 'latest.json');

  if (deps.platform === 'darwin') {
    return installMacosSchedule(deps, frequency, homeDir, outputPath);
  }
  return installLinuxSchedule(deps, frequency, outputPath);
}

async function installMacosSchedule(
  deps: WorktrainReportScheduleDeps,
  frequency: ScheduleFrequency,
  homeDir: string,
  outputPath: string,
): Promise<ScheduleInstallResult> {
  const launchAgentsDir = deps.joinPath(homeDir, 'Library', 'LaunchAgents');
  const plistPath = deps.joinPath(launchAgentsDir, PLIST_FILENAME);

  // Ensure the output directory exists so the scheduled command can write to it.
  const outputDir = deps.joinPath(homeDir, '.workrail', 'data', 'reports');
  try {
    await deps.mkdir(outputDir);
  } catch {
    // Non-fatal: directory may already exist.
  }

  const plistContent = buildReportPlist(
    deps.nodeBinPath,
    deps.worktrainBinPath,
    outputPath,
    homeDir,
    frequency,
  );

  try {
    await deps.writeFile(plistPath, plistContent);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { kind: 'err', message: `Failed to write plist to ${plistPath}: ${msg}` };
  }

  // Attempt to load the plist via launchctl. Non-fatal if this fails (user may need to
  // re-login or load manually). We still report success for the file write.
  const loadResult = await deps.exec('launchctl', ['load', plistPath]);
  if (loadResult.exitCode !== 0) {
    deps.printErr(
      `[report] Warning: plist written but launchctl load failed (exit ${loadResult.exitCode}): ${loadResult.stderr.trim()}`,
    );
    deps.printErr(`[report] You may need to load it manually: launchctl load ${plistPath}`);
  }

  const scheduleDesc = frequency === 'daily' ? 'daily at 6:00 AM' : 'weekly on Mondays at 6:00 AM';
  return {
    kind: 'ok',
    detail: [
      `Schedule installed (${scheduleDesc}).`,
      `Plist: ${plistPath}`,
      `Output: ${outputPath}`,
      `To remove: launchctl unload ${plistPath} && rm ${plistPath}`,
    ].join('\n'),
  };
}

async function installLinuxSchedule(
  deps: WorktrainReportScheduleDeps,
  frequency: ScheduleFrequency,
  outputPath: string,
): Promise<ScheduleInstallResult> {
  const cronExpr = buildCronExpression(frequency);
  const cronLine = `${cronExpr} ${deps.worktrainBinPath} report --days 30 --out ${outputPath}`;

  // Ensure the output directory exists.
  const homeDir = deps.homedir();
  const outputDir = deps.joinPath(homeDir, '.workrail', 'data', 'reports');
  try {
    await deps.mkdir(outputDir);
  } catch {
    // Non-fatal: directory may already exist.
  }

  // Read existing crontab.
  const listResult = await deps.exec('crontab', ['-l']);
  const existingCrontab = listResult.exitCode === 0 ? listResult.stdout : '';

  // Avoid duplicate entries: check if the report line is already present.
  if (existingCrontab.includes('worktrain report')) {
    return {
      kind: 'ok',
      detail: [
        'A worktrain report crontab entry already exists. No changes made.',
        `To update, run: crontab -e`,
      ].join('\n'),
    };
  }

  const newCrontab = existingCrontab.trimEnd() + '\n' + cronLine + '\n';

  // Write the new crontab via a temporary stdin pipe.
  // WHY use 'crontab -' with stdin: it is the POSIX-portable way to set a crontab
  // programmatically without requiring a temp file or interactive editor.
  const writeResult = await deps.exec('bash', ['-c', `echo ${JSON.stringify(newCrontab)} | crontab -`]);
  if (writeResult.exitCode !== 0) {
    const fallback = `Manual install:\n  (crontab -l; echo "${cronLine}") | crontab -`;
    return {
      kind: 'err',
      message: `Failed to write crontab (exit ${writeResult.exitCode}): ${writeResult.stderr.trim()}\n${fallback}`,
    };
  }

  const scheduleDesc = frequency === 'daily' ? 'daily at 6:00 AM' : 'weekly on Mondays at 6:00 AM';
  return {
    kind: 'ok',
    detail: [
      `Schedule installed (${scheduleDesc}).`,
      `Cron: ${cronLine}`,
      `Output: ${outputPath}`,
      `To remove: crontab -e`,
    ].join('\n'),
  };
}
