/**
 * WorkTrain Init Command
 *
 * Guided onboarding for WorkTrain daemon setup. Configures:
 *   1. LLM credentials (Bedrock or Anthropic) -- detection + print instructions
 *   2. Workspace path -- prompts user, writes WORKRAIL_DEFAULT_WORKSPACE to config.json
 *   3. SCM token (GitHub/GitLab) -- prompts user, prints export instructions, never writes to disk
 *   4. triggers.yml -- generates a starter file in the workspace if absent
 *   5. daemon-soul.md -- writes ~/.workrail/daemon-soul.md if absent
 *   6. Smoke test -- runs `workrail list` to verify installation
 *
 * Design invariants:
 * - All I/O is injected via WorktrainInitCommandDeps. Zero direct fs/readline imports.
 * - No secrets are ever written to disk. Token values stay in the user's shell profile.
 * - Each section is skip-if-already-configured (idempotent).
 * - All failures are returned as CliResult failure variants -- never thrown.
 * - The --yes flag skips all prompts and uses safe defaults (for CI / non-TTY use).
 */

import type { CliResult } from '../types/cli-result.js';
import { success, failure } from '../types/cli-result.js';
import { DAEMON_SOUL_TEMPLATE } from '../../daemon/soul-template.js';

// ═══════════════════════════════════════════════════════════════════════════
// DEPENDENCIES
// ═══════════════════════════════════════════════════════════════════════════

/**
 * All I/O operations required by the init command.
 * Inject real implementations in the composition root; inject fakes in tests.
 */
export interface WorktrainInitCommandDeps {
  /** Interactive prompt. Returns defaultValue when --yes is set (see opts.yes). */
  readonly prompt: (question: string, defaultValue?: string) => Promise<string>;
  /** Create directory (recursive: true = mkdir -p). */
  readonly mkdir: (path: string, options: { recursive: boolean }) => Promise<string | undefined>;
  /** Read file contents as UTF-8 string. Throws on ENOENT. */
  readonly readFile: (path: string) => Promise<string>;
  /** Write UTF-8 string to file, creating parent directory first. */
  readonly writeFile: (path: string, content: string) => Promise<void>;
  /** Return true if the path exists (file or directory). */
  readonly exists: (path: string) => Promise<boolean>;
  /** Return the user's home directory. */
  readonly homedir: () => string;
  /** Return the current working directory. Used as the default workspace in --yes mode. */
  readonly cwd: () => string;
  /** Join path segments (same semantics as node:path join). */
  readonly joinPath: (...paths: string[]) => string;
  /** Run the workrail binary and return stdout + success flag. */
  readonly runSmoke: () => Promise<{ readonly ok: boolean; readonly output: string }>;
  /** Print a line to stdout. */
  readonly print: (line: string) => void;
  /** Current process environment. Used to detect existing credentials. */
  readonly env: Readonly<Record<string, string | undefined>>;
}

/**
 * Options for the init command.
 */
export interface WorktrainInitCommandOpts {
  /**
   * When true, skip all interactive prompts and use safe defaults.
   * Intended for CI / non-TTY environments.
   */
  readonly yes?: boolean;
}

// ═══════════════════════════════════════════════════════════════════════════
// SECTION RESULT
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Result of a single onboarding section.
 * Discriminated union -- errors-as-data per repo philosophy.
 */
type SectionResult =
  | { readonly kind: 'skipped'; readonly reason: string }
  | { readonly kind: 'configured'; readonly summary: string }
  | { readonly kind: 'warning'; readonly summary: string; readonly warning: string }
  | { readonly kind: 'error'; readonly message: string };

// ═══════════════════════════════════════════════════════════════════════════
// TRIGGERS.YML TEMPLATE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Starter triggers.yml content.
 * Uses provider: generic for the starter trigger, as the simplest thing that
 * works without external configuration. Workspace path is interpolated at
 * generation time.
 *
 * Polling providers (github_queue_poll, github_prs_poll, gitlab_poll) also
 * exist -- see src/trigger/polling-scheduler.ts -- but they need credentials
 * and repository configuration, so they are not what a starter file should
 * hand someone.
 */
function buildTriggersYml(workspacePath: string): string {
  return `# WorkRail trigger configuration
# Generated by worktrain init
#
# This file is read by the WorkRail daemon (workrail daemon --workspace <path>).
# Add or edit triggers to control which workflows run and when.

triggers:
  - id: my-first-trigger
    provider: generic
    workflowId: wr.coding-task
    workspacePath: ${workspacePath}
    goal: "Handle incoming coding task"
    # hmacSecret: $WEBHOOK_SECRET   # uncomment and set env var to enable HMAC validation
    #
    # To fire this trigger manually:
    #   curl -X POST http://localhost:3200/webhook/my-first-trigger \\
    #        -H "Content-Type: application/json" \\
    #        -d '{"task": "describe the task here"}'
`;
}

// ═══════════════════════════════════════════════════════════════════════════
// SECTION IMPLEMENTATIONS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Section 1: LLM Credentials
 *
 * Detects existing credentials from the environment. If none are found,
 * prints instructions for setting them. Never writes credentials to disk.
 */
async function runCredentialsSection(
  deps: WorktrainInitCommandDeps,
  opts: WorktrainInitCommandOpts,
): Promise<SectionResult> {
  const hasBedrock =
    !!deps.env['AWS_PROFILE'] || !!deps.env['AWS_ACCESS_KEY_ID'];
  const hasAnthropic = !!deps.env['ANTHROPIC_API_KEY'];

  if (hasBedrock) {
    return {
      kind: 'skipped',
      reason: `Bedrock credentials detected (AWS_PROFILE=${deps.env['AWS_PROFILE'] ?? 'set'})`,
    };
  }
  if (hasAnthropic) {
    return {
      kind: 'skipped',
      reason: 'Anthropic API key detected (ANTHROPIC_API_KEY is set)',
    };
  }

  deps.print('');
  deps.print('LLM credentials not found.');

  let choice: string;
  if (opts.yes) {
    choice = 'anthropic';
    deps.print('  Using default: Anthropic API key (--yes mode)');
  } else {
    deps.print('  Which LLM provider do you want to use?');
    deps.print('    1) AWS Bedrock (requires AWS SSO profile)');
    deps.print('    2) Anthropic API key (direct access)');
    choice = await deps.prompt('  Enter 1 or 2 [2]: ', '2');
  }

  if (choice === '1') {
    deps.print('');
    deps.print('  To use AWS Bedrock, set your AWS SSO profile:');
    deps.print('    export AWS_PROFILE=your-sso-profile-name');
    deps.print('  Then run: aws sso login --profile your-sso-profile-name');
    return {
      kind: 'configured',
      summary: 'Printed Bedrock setup instructions (set AWS_PROFILE in your shell profile)',
    };
  } else {
    deps.print('');
    deps.print('  To use the Anthropic API, set your API key:');
    deps.print('    export ANTHROPIC_API_KEY=sk-ant-...');
    deps.print('  Add this line to ~/.zshrc or ~/.bashrc to persist across sessions.');
    return {
      kind: 'configured',
      summary: 'Printed Anthropic API key instructions (set ANTHROPIC_API_KEY in your shell profile)',
    };
  }
}

/**
 * Section 2: Workspace Path
 *
 * Prompts for the default workspace directory. Writes WORKRAIL_DEFAULT_WORKSPACE
 * to ~/.workrail/config.json via JSON merge so the daemon uses it as a default.
 *
 * Returns the prompted workspace path for use by subsequent sections.
 * Returns empty string if skipped (--yes with existing config).
 */
async function runWorkspaceSection(
  deps: WorktrainInitCommandDeps,
  opts: WorktrainInitCommandOpts,
): Promise<{ result: SectionResult; workspacePath: string }> {
  const configDir = deps.joinPath(deps.homedir(), '.workrail');
  const configPath = deps.joinPath(configDir, 'config.json');

  // Read existing config to check if already set
  let existingConfig: Record<string, unknown> = {};
  try {
    const raw = await deps.readFile(configPath);
    existingConfig = JSON.parse(raw) as Record<string, unknown>;
  } catch {
    // Config file doesn't exist or isn't valid JSON -- we'll create/overwrite
  }

  if (typeof existingConfig['WORKRAIL_DEFAULT_WORKSPACE'] === 'string' &&
      existingConfig['WORKRAIL_DEFAULT_WORKSPACE'].trim() !== '') {
    const existing = existingConfig['WORKRAIL_DEFAULT_WORKSPACE'] as string;
    if (opts.yes) {
      return {
        result: {
          kind: 'skipped',
          reason: `Workspace already set to: ${existing}`,
        },
        workspacePath: existing,
      };
    }
    // Even if set, let the user change it
    deps.print('');
    deps.print(`  Current workspace: ${existing}`);
  }

  let workspacePath: string;
  if (opts.yes) {
    // Default to cwd (the repo root) rather than homedir -- most users run this
    // from inside their project directory and don't want triggers.yml in ~.
    workspacePath = deps.cwd();
    deps.print(`  Using default workspace: ${workspacePath} (--yes mode)`);
  } else {
    deps.print('');
    deps.print('  Enter the default workspace path for the daemon.');
    deps.print('  This is the root directory of the repository the agent will work in.');
    const defaultPath = typeof existingConfig['WORKRAIL_DEFAULT_WORKSPACE'] === 'string'
      ? existingConfig['WORKRAIL_DEFAULT_WORKSPACE']
      : deps.homedir();
    workspacePath = await deps.prompt(`  Workspace path [${defaultPath}]: `, defaultPath);
    if (!workspacePath.trim()) {
      workspacePath = defaultPath;
    }
  }

  // Validate path existence (warn, don't block)
  const pathExists = await deps.exists(workspacePath);
  let warning: string | undefined;
  if (!pathExists) {
    warning = `Directory not found: ${workspacePath}. Create it before starting the daemon.`;
  }

  // Write to config.json via JSON merge
  const updatedConfig: Record<string, unknown> = {
    ...existingConfig,
    WORKRAIL_DEFAULT_WORKSPACE: workspacePath,
  };

  try {
    await deps.mkdir(configDir, { recursive: true });
    await deps.writeFile(configPath, JSON.stringify(updatedConfig, null, 2) + '\n');
  } catch (err) {
    return {
      result: {
        kind: 'error',
        message: `Failed to write config.json: ${err instanceof Error ? err.message : String(err)}`,
      },
      workspacePath,
    };
  }

  if (warning) {
    return {
      result: {
        kind: 'warning',
        summary: `Workspace path written to config.json: ${workspacePath}`,
        warning,
      },
      workspacePath,
    };
  }

  return {
    result: {
      kind: 'configured',
      summary: `Workspace path written to config.json: ${workspacePath}`,
    },
    workspacePath,
  };
}

/**
 * Section 3: SCM Token (GitHub / GitLab)
 *
 * Prompts for a GitHub or GitLab personal access token.
 * NEVER writes the literal token to disk.
 * Prints export instructions and notes that the token should be set in shell profile.
 */
async function runScmTokenSection(
  deps: WorktrainInitCommandDeps,
  opts: WorktrainInitCommandOpts,
): Promise<SectionResult> {
  if (opts.yes) {
    return {
      kind: 'skipped',
      reason: 'SCM token setup skipped in --yes mode (set GITHUB_TOKEN or GITLAB_TOKEN manually)',
    };
  }

  const hasGithub = !!deps.env['GITHUB_TOKEN'];
  const hasGitlab = !!deps.env['GITLAB_TOKEN'];
  if (hasGithub && hasGitlab) {
    return { kind: 'skipped', reason: 'GITHUB_TOKEN and GITLAB_TOKEN already set' };
  }
  if (hasGithub) {
    return { kind: 'skipped', reason: 'GITHUB_TOKEN already set' };
  }
  if (hasGitlab) {
    return { kind: 'skipped', reason: 'GITLAB_TOKEN already set' };
  }

  deps.print('');
  deps.print('  GitHub / GitLab token (optional -- press Enter to skip).');
  deps.print('  Required if you want to use polling triggers for MR/PR reviews.');
  const token = await deps.prompt('  Personal access token: ', '');

  if (!token.trim()) {
    return {
      kind: 'skipped',
      reason: 'No token provided (skipped)',
    };
  }

  deps.print('');
  deps.print('  Add the following to your ~/.zshrc or ~/.bashrc:');
  // Print the actual token in the export instruction (user requested this to copy)
  // WHY: The token is printed to stdout during an interactive session. It is never
  // written to any file on disk. The user copies it to their shell profile themselves.
  deps.print(`    export GITHUB_TOKEN=${token}`);
  deps.print('  (Use GITLAB_TOKEN instead if you are using GitLab.)');
  deps.print('  Then run: source ~/.zshrc  (or restart your terminal)');

  return {
    kind: 'configured',
    summary: 'Printed token export instructions (token NOT written to disk)',
  };
}

/**
 * Section 4: triggers.yml
 *
 * Generates a starter triggers.yml in the workspace directory if one doesn't exist.
 * Uses provider: generic (the only MVP-supported provider).
 */
async function runTriggersSection(
  deps: WorktrainInitCommandDeps,
  opts: WorktrainInitCommandOpts,
  workspacePath: string,
): Promise<SectionResult> {
  const triggersPath = deps.joinPath(workspacePath, 'triggers.yml');
  const exists = await deps.exists(triggersPath);

  if (exists) {
    return { kind: 'skipped', reason: `${triggersPath} already exists` };
  }

  if (!workspacePath.trim()) {
    return {
      kind: 'skipped',
      reason: 'Workspace path not set -- skipping triggers.yml generation',
    };
  }

  const content = buildTriggersYml(workspacePath);

  try {
    // Workspace directory may not exist yet (user was warned above)
    await deps.mkdir(workspacePath, { recursive: true });
    await deps.writeFile(triggersPath, content);
  } catch (err) {
    return {
      kind: 'error',
      message: `Failed to write triggers.yml: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  return {
    kind: 'configured',
    summary: `Written: ${triggersPath}`,
  };
}

/**
 * Section 5: daemon-soul.md
 *
 * Writes ~/.workrail/daemon-soul.md if it doesn't already exist.
 * This file customizes the agent's behavior for every daemon session.
 */
async function runDaemonSoulSection(
  deps: WorktrainInitCommandDeps,
): Promise<SectionResult> {
  const soulPath = deps.joinPath(deps.homedir(), '.workrail', 'daemon-soul.md');
  const exists = await deps.exists(soulPath);

  if (exists) {
    return { kind: 'skipped', reason: `${soulPath} already exists` };
  }

  try {
    await deps.mkdir(deps.joinPath(deps.homedir(), '.workrail'), { recursive: true });
    await deps.writeFile(soulPath, DAEMON_SOUL_TEMPLATE);
  } catch (err) {
    return {
      kind: 'error',
      message: `Failed to write daemon-soul.md: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  return {
    kind: 'configured',
    summary: `Written: ${soulPath}`,
  };
}

/**
 * Section 6: Smoke test
 *
 * Runs `workrail list` to verify the installation is working.
 */
async function runSmokeSection(
  deps: WorktrainInitCommandDeps,
): Promise<SectionResult> {
  const result = await deps.runSmoke();
  if (result.ok) {
    return {
      kind: 'configured',
      summary: `workrail list succeeded:\n${result.output}`,
    };
  }
  return {
    kind: 'warning',
    summary: 'Smoke test failed (installation may not be complete)',
    warning: result.output || 'workrail list returned an error. Is workrail installed and on your PATH?',
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// MAIN COMMAND
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Execute the `worktrain init` command.
 *
 * Runs 6 onboarding sections in order. Each section is idempotent (skip-if-configured).
 * Returns CliResult success if the flow completes (even if some sections have warnings).
 * Returns CliResult failure only for unrecoverable errors (e.g., config write failure).
 */
export async function executeWorktrainInitCommand(
  deps: WorktrainInitCommandDeps,
  opts: WorktrainInitCommandOpts = {},
): Promise<CliResult> {
  deps.print('');
  deps.print('WorkTrain Onboarding');
  deps.print('════════════════════════════════════════');
  if (opts.yes) {
    deps.print('Running in non-interactive mode (--yes). Using safe defaults.');
  }
  deps.print('');

  const sectionLabels = [
    'LLM credentials',
    'Workspace',
    'SCM token',
    'triggers.yml',
    'daemon-soul.md',
    'Smoke test',
  ];

  // Section 1: Credentials
  deps.print('[ 1/6 ] LLM credentials');
  const credResult = await runCredentialsSection(deps, opts);
  printSectionResult(deps, credResult);

  // Section 2: Workspace
  deps.print('[ 2/6 ] Workspace');
  const { result: wsResult, workspacePath } = await runWorkspaceSection(deps, opts);
  printSectionResult(deps, wsResult);
  if (wsResult.kind === 'error') {
    return failure(wsResult.message, {
      suggestions: ['Check write permissions for ~/.workrail/config.json'],
    });
  }

  // Section 3: SCM token
  deps.print('[ 3/6 ] SCM token (GitHub / GitLab)');
  const scmResult = await runScmTokenSection(deps, opts);
  printSectionResult(deps, scmResult);

  // Section 4: triggers.yml
  deps.print('[ 4/6 ] triggers.yml');
  const triggersResult = await runTriggersSection(deps, opts, workspacePath);
  printSectionResult(deps, triggersResult);
  // printSectionResult already prints the error message for kind: 'error' -- no extra print needed.
  // Execution continues regardless (triggers.yml failure is non-fatal).

  // Section 5: daemon-soul.md
  deps.print('[ 5/6 ] daemon-soul.md');
  const soulResult = await runDaemonSoulSection(deps);
  printSectionResult(deps, soulResult);
  // printSectionResult already prints the error message for kind: 'error' -- no extra print needed.
  // Execution continues regardless (daemon-soul.md failure is non-fatal).

  // Section 6: Smoke test
  deps.print('[ 6/6 ] Smoke test');
  const smokeResult = await runSmokeSection(deps);
  printSectionResult(deps, smokeResult);

  deps.print('');
  deps.print('Setup complete. To start the daemon:');
  deps.print(`  workrail daemon --workspace ${workspacePath || '<your-workspace>'}`);
  deps.print('');

  // Suppress unused variable warning for sectionLabels
  void sectionLabels;

  return success({
    message: 'WorkTrain onboarding complete',
    details: buildSummaryDetails(credResult, wsResult, scmResult, triggersResult, soulResult, smokeResult),
  });
}

// ═══════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════

function printSectionResult(deps: WorktrainInitCommandDeps, result: SectionResult): void {
  switch (result.kind) {
    case 'skipped':
      deps.print(`  Skipped: ${result.reason}`);
      break;
    case 'configured':
      deps.print(`  Done: ${result.summary}`);
      break;
    case 'warning':
      deps.print(`  Done: ${result.summary}`);
      deps.print(`  Warning: ${result.warning}`);
      break;
    case 'error':
      deps.print(`  Error: ${result.message}`);
      break;
  }
  deps.print('');
}

function buildSummaryDetails(...results: SectionResult[]): string[] {
  return results.map((r) => {
    switch (r.kind) {
      case 'skipped':    return `skipped: ${r.reason}`;
      case 'configured': return `configured: ${r.summary}`;
      case 'warning':    return `warning: ${r.summary} -- ${r.warning}`;
      case 'error':      return `error: ${r.message}`;
    }
  });
}
